# Generated by Django 4.1.2 on 2022-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwreye_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_source', models.CharField(blank=True, max_length=255)),
                ('blur_kernel_size_1', models.FloatField(blank=True, max_length=255, null=True)),
                ('blur_kernel_size_2', models.FloatField(blank=True, max_length=255, null=True)),
                ('savgol_window_size_1', models.FloatField(blank=True, max_length=255, null=True)),
                ('savgol_window_size_2', models.FloatField(blank=True, max_length=255, null=True)),
                ('alpha_1', models.FloatField(blank=True, max_length=255, null=True)),
                ('alpha_2', models.FloatField(blank=True, max_length=255, null=True)),
                ('alpha_3', models.FloatField(blank=True, max_length=255, null=True)),
                ('alpha_4', models.FloatField(blank=True, max_length=255, null=True)),
                ('control_param_1', models.FloatField(blank=True, max_length=255, null=True)),
                ('control_param_2', models.FloatField(blank=True, max_length=255, null=True)),
                ('control_param_3', models.FloatField(blank=True, max_length=255, null=True)),
                ('control_param_4', models.FloatField(blank=True, max_length=255, null=True)),
                ('str_out1', models.FloatField(blank=True, max_length=255, null=True)),
                ('str_out2', models.FloatField(blank=True, max_length=255, null=True)),
                ('str_out3', models.FloatField(blank=True, max_length=255, null=True)),
                ('str_IP_address', models.CharField(blank=True, max_length=255, null=True)),
                ('modbus_port', models.CharField(blank=True, max_length=255, null=True)),
                ('start_TCP_client', models.CharField(blank=True, max_length=255, null=True)),
                ('str_saveinput', models.CharField(blank=True, max_length=255, null=True)),
                ('str_saveoutput', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
